_prefs: 
  mapid: laurenancona.2ff8c154
  saveCenter: false
_properties: {}
attribution: "<a href=\"https://twitter.com/laurenancona\" />Lauren Ancona</a> | <a href=\"https://phillypopemap.com/sources.html\" /> Sources </a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -75.1641
  - 39.9577
  - 14
description: ''
format: "png8:m=h:c=32"
interactivity_layer: laurenancona.b6b3d96e
layers: 


# basemap features
  - waterway
  - water
  - philadelphia-city-limits
  - landuse
  - tunnel
  - curbproj
  - bridge
  #polygons
  - secure-vehicle-perimeter-fri-10a
  - secure-vehicle-perimeter-fri-10p_3857
  - secure-vehicle-independence-fri-10p
  - secure-perimeter-12-20th-6a
  - secure-perimeter-thur-10p
  - independence-mall-secure-perimeter-sat-6am
  - traffic-boxes-fri-6-10pm
  - parkway-ticketed-sunday
# lines
  - road
  - highways
  - walking
  - authorized-veh-only-fri-6p
  - authorized-vehicles-only
# labels
  - highways.label
  - water.label
  - road_label
  - bridge.label
  - authorized-vehicle-only_labels
# polygon labels
  - secure-vehicle-perimeter-fri-10a.labels
  - secure-vehicle-perimeter-fri-10p_3857.labels
  - secure-vehicle-independence-fri-10p.labels
  - independence-mall-secure-perimeter-sat-6am.labels
  - secure-perimeter-12-20th-6a.labels 
  - secure-perimeter-thur-10p.labels
  - traffic-boxes-fri-6-10pm.labels
  - parkway-ticketed-sunday.labels
# points
  - transit-stations
  - jumbotrons
  - hospitals
  - entrances
maxzoom: 18
minzoom: 13
name: philly-pope-baselayer
source: "mapbox:///mapbox.mapbox-streets-v5,laurenancona.h8rozuxr,laurenancona.697zm2t9,laurenancona.ae5b1a3d,laurenancona.b6b3d96e"
styles: 
  - style.mss
  - roads.mss
  - poped.mss
  - labels.mss
template: ''
